### ISSUE TITLE
Ruby group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by HectorTorresE** [rskinnerc/catalog-of-my-things#24]
This project has 3 team members: @HectorTorresE (Team member 1), @wandergithub (Team member 2), @rskinnerc (Team member 3)
Project link: https://github.com/rskinnerc/catalog-of-my-things/projects/1

**Comment by FrederickMih** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by rskinnerc** [comment]
Thank you @FrederickMih
